---
title: "Biodiversity Modelling Summer School"
author:
- name: Dominique Gravel, Ph.D.
  affiliation: Université de Sherbrooke
- name: Andrew MacDonald, Ph.D.
  affiliation: Université de Sherbrooke
date: "2021-08-16"
description: |
  Evaluating ecological models with data
output:
  distill::distill_article:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages
```

## Probabilities and distributions  

**16 August**  

know your data, define your problem.

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

```{r slides-intro, echo=FALSE, fig.cap="[Slides](slides/index.html)"}
xaringanExtra::embed_xaringan(url = "slides/01_introduction.html", ratio = "16:9")
```


```{r slides-definitions, echo=FALSE, fig.cap="[Slides](slides/index.html)"}
xaringanExtra::embed_xaringan(url = "slides/02_definitions.html", ratio = "16:9")
```


```{r slides-rules, echo=FALSE, fig.cap="[Slides](slides/index.html)"}
xaringanExtra::embed_xaringan(url = "slides/03_rules.html", ratio = "16:9")
```


```{r slides-problem, echo=FALSE, fig.cap="[Slides](slides/index.html)"}
xaringanExtra::embed_xaringan(url = "slides/04_problem.html", ratio = "16:9")
```


```{r slides-solutions, echo=FALSE, fig.cap="[Slides](slides/index.html)"}
xaringanExtra::embed_xaringan(url = "slides/05_solutions.html", ratio = "16:9")
```



### Maximum likelihood methods  

*18 August*  

write down equations for your model.

```
August 20	Optimization algorithms: reveal the capacities of computers to solve complex problems numerically.
August 23	Bayesian statistics: how to properly represent uncertainty in ecological models.
August 25	Sampling algorithms: evaluating posterior distributions by your own.
```
